### ISSUE TITLE
GPT answering out of context

### ISSUE THREAD

**Issue by alijavaidistar** [atomic14/command_line_chatgpt#8]
Hello,

I have cloned the exact code and instructions, input my API, ran the code, and it worked. However, I am having a problem where GPT is answering questions of context, please see the attached image, any thoughts?

![Screenshot 2023-06-06 163233](https://github.com/atomic14/command_line_chatgpt/assets/131304144/ccdb01e3-0a35-4321-9aa9-66415506576e)

**Comment by Xanovavich** [comment]
Idk man, im just a kid

**Comment by alijavaidistar** [comment]
This is resolved, all it needs is more instructions so that the program does not go out of context.
